providers = ["php", "node"]

[phases.setup]
# Memaksa install PHP 8.3 dan ekstensi yang Anda butuhkan
nixPkgs = [
    "php83", 
    "php83Extensions.gd", 
    "php83Extensions.zip", 
    "php83Extensions.intl", 
    "php83Extensions.pdo", 
    "php83Extensions.pdo_pgsql", 
    "php83Extensions.redis",
    "git", 
    "unzip"
]

[phases.build]
# Perintah build untuk Frontend dan Backend
cmds = [
    "npm install && npm run build", 
    "mkdir -p storage/framework/sessions storage/framework/views storage/framework/cache",
    "composer install --optimize-autoloader --no-dev --no-interaction"
]

[start]
# Perintah untuk menjalankan aplikasi
cmd = "php artisan migrate --force && php artisan serve --host=0.0.0.0 --port=$PORT"
